INSERT INTO permissions (name, created_at, updated_at) VALUES
    ('EDIT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('DELETE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('CREATE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('EXPORT_EXCEL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('VIEW', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);